server:
  port: 0

spring:
  application:
    name: sensor-data-collector
  datasource:
    url: jdbc:postgresql://localhost:26257/sensor_db?user=root&password=
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true  # Corregido (antes "fetch-register")
    register-with-eureka: true  # Corregido (antes "register-whit-eureka")
  instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always