server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: SensorDataController
              uri: lb://sensor-data-collector
              predicates:
                - Path=/api/conjunta/2p/sensor-readings/**
              filters:
                - StripPrefix=3
            - id: analyzer-service
              uri: lb://ENVIRONMENTAL-ANALYZER
              predicates:
                - Path=/api/conjunta/2p/analyzer/**
              filters:
                - StripPrefix=3
            - id: notification-service
              uri: lb://NOTIFICATION-DISPATCHER
              predicates:
                - Path=/api/conjunta/2p/notification/**
              filters:
                - StripPrefix=3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always