version: '3.8'

services:
  cockroach1:
    image: cockroachdb/cockroach:latest
    container_name: crdb-nodo1
    hostname: crdb-nodo1  # Importante para el DNS interno
    ports:
      - "26257:26257"  # SQL (externo:26257 → interno:26257)
      - "8080:8080"    # UI
    volumes:
      - cockroach1:/cockroach/cockroach-data
    command: start-single-node --insecure --advertise-addr=crdb-nodo1

  cockroach2:
    image: cockroachdb/cockroach:latest
    container_name: crdb-nodo2
    hostname: crdb-nodo2
    ports:
      - "26258:26257"  # SQL (externo:26258 → interno:26257)
      - "8081:8080"    # UI
    volumes:
      - cockroach2:/cockroach/cockroach-data
    command: start --insecure --store=nodo2 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=crdb-nodo1:26257 --advertise-addr=crdb-nodo2

  cockroach3:
    image: cockroachdb/cockroach:latest
    container_name: crdb-nodo3
    hostname: crdb-nodo3
    ports:
      - "26259:26257"  # SQL (externo:26259 → interno:26257)
      - "8082:8080"    # UI
    volumes:
      - cockroach3:/cockroach/cockroach-data
    command: start --insecure --store=nodo3 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=crdb-nodo1:26257 --advertise-addr=crdb-nodo3

volumes:
  cockroach1:
  cockroach2:
  cockroach3:  # Corregí el typo (antes decía "cockroach3")